### ISSUE TITLE
Count Values Are Not Dynamic

### ISSUE THREAD

**Issue by JHeroGR** [pjonp/pjTestBot#3]
So far only the Follower Count Numbers are dynamic when you change the Font Size, when I enable another Goal like Tip Count Numbers, and check the Font Size, it doesn't increase in Font Size like the Follower Count Numbers.
Follower Count
![image](https://user-images.githubusercontent.com/32202517/130911227-cdc56d14-9309-4097-9df1-9bc2056e2846.png)
Tip Count
![image](https://user-images.githubusercontent.com/32202517/130911253-603a4e77-a019-4d45-8858-ae7f2c098d28.png)
Subscriber Count
![image](https://user-images.githubusercontent.com/32202517/130911376-fae2a201-14e4-434e-93e1-7ea5823a1a49.png)
So far Subscriber Count is dynamic like Follower Count, but for Tip Count and Cheer Count I believe are **not** dynamic.

**Comment by pjonp** [comment]
Thank you for the comment.

The font size for the current amount and the goal is based on the number of characters in the goal. Since the tip goal is 7 characters long, its font size is lowered to fit inside the container. If you set the tip goal to $1 with the trailing .00 setting turned off, you will see it match the last image you have, or if you set the follower goal to 1000100 you will see that shrink to size in the tip image you posted.

I will add an override setting for each goal that will force the numbers to the max font-size setting.

**Comment by pjonp** [comment]
Each option now has a minimum Font Size option in the settings. Thanks again for the feedback.

Feel free to tag me in the StreamElements Discord if you find other issues or ideas for improvement!
